# Generated by Django 5.0.2 on 2024-03-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("robot_app", "0002_remove_customuser_name_alter_testuser_feeling_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="feeling",
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="score",
            field=models.FloatField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="testuser",
            name="feeling",
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="testuser",
            name="score",
            field=models.FloatField(default=None, max_length=10, null=True),
        ),
    ]
