# Generated by Django 5.0.2 on 2024-03-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("robot_app", "0004_rename_feeling_customuser_r1feeling_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="r1score",
            new_name="r1feeling1",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="r2score",
            new_name="r1feeling2",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="age",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="contact_num",
        ),
        migrations.RemoveField(
            model_name="testuser",
            name="feeling",
        ),
        migrations.RemoveField(
            model_name="testuser",
            name="score",
        ),
        migrations.AddField(
            model_name="customuser",
            name="r1feeling3",
            field=models.FloatField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="r2feeling1",
            field=models.FloatField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="r2feeling2",
            field=models.FloatField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="r2feeling3",
            field=models.FloatField(default=None, max_length=10, null=True),
        ),
    ]
