# Generated by Django 5.0.2 on 2024-03-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("robot_app", "0005_rename_r1score_customuser_r1feeling1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="r1feeling1",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="r1feeling2",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="r1feeling3",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="r2feeling1",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="r2feeling2",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="r2feeling3",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
